# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/gosuri/uilive"
  version = "0.0.1"

[prune]
  go-tests = true
  unused-packages = true
