version: '2'
services:
  app:
    build:
      context: ..
      dockerfile: .buildkite/Dockerfile
    volumes:
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - GITHUB_RELEASE_ACCESS_TOKEN
      - DOCKER_HUB_TRIGGER_TOKEN
