steps:
  - label: ':hammer: Tests'
    command: 'godep go test ./core'
    plugins:
      - docker-compose#v3.0.3:
          run: app
          config:
            - .buildkite/docker-compose.yml
  - wait
  - label: ':package: Build & Release'
    command: .buildkite/publish.sh
    plugins:
      - docker-compose#v3.0.3:
          run: app
          shell: false
          config:
            - .buildkite/docker-compose.yml
    # branches: 'master'
