steps:
  - label: ':hammer: Tests'
    command: 'godep go test ./core'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
      BUILDKITE_DOCKER_COMPOSE_FILE: .buildkite/docker-compose.yml

  - block: ':shipit: Release?'
    branches: 'master'

  - label: ':package: Build & Release'
    command: 'go install && aws s3 cp /go/bin/committer s3://zenops/packages/'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
      BUILDKITE_DOCKER_COMPOSE_FILE: .buildkite/docker-compose.yml
    branches: 'master'
