steps:
  - label: ':hammer: Tests'
    command: 'godep go test ./core'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
      BUILDKITE_DOCKER_COMPOSE_FILE: .buildkite/docker-compose.yml
  - label: ':package: Build & Release'
    command: .buildkite/publish.sh
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
      BUILDKITE_DOCKER_COMPOSE_FILE: .buildkite/docker-compose.yml
    branches: 'master'
