on:
  push:
    branches:
    - main

name: Release

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create release
        id: version
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          ci/install-crom.sh
          VERSION=$(.bin/crom get next-release)
          gh release create $VERSION --generate-notes --target $(git rev-parse HEAD) --draft
          echo "::set-output name=version::$VERSION"

  publish:
    uses: ./.github/workflows/create-artifacts.yml
    needs: create-release
    with:
      version: ${{ needs.create-release.outputs.version }}
      
  promote-draft:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - publish
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: undraft release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release edit ${{ needs.create-release.outputs.version }} --draft=false

  clean-draft:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - publish
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v3
      - name: delete draft release release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release delete ${{ needs.create-release.outputs.version }} --yes