on: [pull_request]

name: Continuous integration

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create pre-release
        id: version
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          set -eux
          ci/install-crom.sh
          VERSION=$(.bin/crom get pre-release)
          echo "Creating release $VERSION"
          echo "::set-output name=version::$VERSION"
          gh release create $VERSION --generate-notes --prerelease --target ${{ github.event.pull_request.head.sha }} --draft

  publish:
    uses: ./.github/workflows/create-artifacts.yml
    needs: create-release
    with:
      version: ${{ needs.create-release.outputs.version }}

  promote-draft:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - publish
    steps:
      - uses: actions/checkout@v3
      - name: undraft release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release edit ${{ needs.create-release.outputs.version }} --draft=false

  clean-draft:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - publish
    if: ${{ failure() && needs.create-release.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: delete draft release release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release delete ${{ needs.create-release.outputs.version }} --yes
